//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCT.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ActivitiesColumns : global::System.Configuration.ApplicationSettingsBase {
        
        private static ActivitiesColumns defaultInstance = ((ActivitiesColumns)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ActivitiesColumns())));
        
        public static ActivitiesColumns Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Email address.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Email address.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EMAIL")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
        }
        
        /// <summary>
        /// First name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("First name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FIRST NAME")]
        public string FirstName {
            get {
                return ((string)(this["FirstName"]));
            }
        }
        
        /// <summary>
        /// Middle name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Middle name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MIDDLE NAME")]
        public string MiddleName {
            get {
                return ((string)(this["MiddleName"]));
            }
        }
        
        /// <summary>
        /// Last name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Last name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAST NAME")]
        public string LastName {
            get {
                return ((string)(this["LastName"]));
            }
        }
        
        /// <summary>
        /// Job title.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Job title.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JOB TITLE")]
        public string JobTitle {
            get {
                return ((string)(this["JobTitle"]));
            }
        }
        
        /// <summary>
        /// Company name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Company name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COMPANY NAME")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
        }
        
        /// <summary>
        /// Work phone.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Work phone.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WORK PHONE")]
        public string WorkPhone {
            get {
                return ((string)(this["WorkPhone"]));
            }
        }
        
        /// <summary>
        /// Home phone.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Home phone.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HOME PHONE")]
        public string HomePhone {
            get {
                return ((string)(this["HomePhone"]));
            }
        }
        
        /// <summary>
        /// Address line 1.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Address line 1.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADDRESS LINE 1")]
        public string Address1 {
            get {
                return ((string)(this["Address1"]));
            }
        }
        
        /// <summary>
        /// Address line 2.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Address line 2.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADDRESS LINE 2")]
        public string Address2 {
            get {
                return ((string)(this["Address2"]));
            }
        }
        
        /// <summary>
        ///  Address line 3.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute(" Address line 3.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADDRESS LINE 3")]
        public string Address3 {
            get {
                return ((string)(this["Address3"]));
            }
        }
        
        /// <summary>
        /// City.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("City.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CITY")]
        public string City {
            get {
                return ((string)(this["City"]));
            }
        }
        
        /// <summary>
        /// State.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("State.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STATE")]
        public string State {
            get {
                return ((string)(this["State"]));
            }
        }
        
        /// <summary>
        /// US state or province.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("US state or province.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("US STATE/CA PROVINCE")]
        public string StateProvince {
            get {
                return ((string)(this["StateProvince"]));
            }
        }
        
        /// <summary>
        /// Country.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Country.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COUNTRY")]
        public string Country {
            get {
                return ((string)(this["Country"]));
            }
        }
        
        /// <summary>
        /// Postal code.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Postal code.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZIP/POSTAL CODE")]
        public string PostalCode {
            get {
                return ((string)(this["PostalCode"]));
            }
        }
        
        /// <summary>
        /// Sub-postal code.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Sub-postal code.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUB ZIP/POSTAL CODE")]
        public string SubPostalCode {
            get {
                return ((string)(this["SubPostalCode"]));
            }
        }
        
        /// <summary>
        /// Custom field 1.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 1.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 1")]
        public string CustomField1 {
            get {
                return ((string)(this["CustomField1"]));
            }
        }
        
        /// <summary>
        /// Custom field 2.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 2.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 2")]
        public string CustomField2 {
            get {
                return ((string)(this["CustomField2"]));
            }
        }
        
        /// <summary>
        /// Custom field 3.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 3.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 3")]
        public string CustomField3 {
            get {
                return ((string)(this["CustomField3"]));
            }
        }
        
        /// <summary>
        /// Custom field 4.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 4.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 4")]
        public string CustomField4 {
            get {
                return ((string)(this["CustomField4"]));
            }
        }
        
        /// <summary>
        /// Custom field 5.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 5.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 5")]
        public string CustomField5 {
            get {
                return ((string)(this["CustomField5"]));
            }
        }
        
        /// <summary>
        /// Custom field 6.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 6.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 6")]
        public string CustomField6 {
            get {
                return ((string)(this["CustomField6"]));
            }
        }
        
        /// <summary>
        /// Custom field 7.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 7.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 7")]
        public string CustomField7 {
            get {
                return ((string)(this["CustomField7"]));
            }
        }
        
        /// <summary>
        /// Custom field 8.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 8.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 8")]
        public string CustomField8 {
            get {
                return ((string)(this["CustomField8"]));
            }
        }
        
        /// <summary>
        /// Custom field 9.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 9.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 9")]
        public string CustomField9 {
            get {
                return ((string)(this["CustomField9"]));
            }
        }
        
        /// <summary>
        /// Custom field 10.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 10.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 10")]
        public string CustomField10 {
            get {
                return ((string)(this["CustomField10"]));
            }
        }
        
        /// <summary>
        /// Custom field 11.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 11.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 11")]
        public string CustomField11 {
            get {
                return ((string)(this["CustomField11"]));
            }
        }
        
        /// <summary>
        /// Custom field 12.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 12.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 12")]
        public string CustomField12 {
            get {
                return ((string)(this["CustomField12"]));
            }
        }
        
        /// <summary>
        /// Custom field 13.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 13.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 13")]
        public string CustomField13 {
            get {
                return ((string)(this["CustomField13"]));
            }
        }
        
        /// <summary>
        /// Custom field 14.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 14.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 14")]
        public string CustomField14 {
            get {
                return ((string)(this["CustomField14"]));
            }
        }
        
        /// <summary>
        /// Custom field 15.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Custom field 15.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOM FIELD 15")]
        public string CustomField15 {
            get {
                return ((string)(this["CustomField15"]));
            }
        }
    }
}
