//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCT.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Endpoints : global::System.Configuration.ApplicationSettingsBase {
        
        private static Endpoints defaultInstance = ((Endpoints)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Endpoints())));
        
        public static Endpoints Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// API access URL.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("API access URL.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.constantcontact.com/v2/")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
        }
        
        /// <summary>
        /// Access an activity.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access an activity.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities/{0}")]
        public string Activity {
            get {
                return ((string)(this["Activity"]));
            }
        }
        
        /// <summary>
        /// List activities.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("List activities.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities")]
        public string Activities {
            get {
                return ((string)(this["Activities"]));
            }
        }
        
        /// <summary>
        /// Export contacts linked to an activity.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Export contacts linked to an activity.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities/exportcontacts")]
        public string ExportContactsActivity {
            get {
                return ((string)(this["ExportContactsActivity"]));
            }
        }
        
        /// <summary>
        /// Clear the list of activities.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Clear the list of activities.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities/clearlists")]
        public string ClearListsActivity {
            get {
                return ((string)(this["ClearListsActivity"]));
            }
        }
        
        /// <summary>
        /// Remove from list.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Remove from list.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities/removefromlists")]
        public string RemoveFromListsActivity {
            get {
                return ((string)(this["RemoveFromListsActivity"]));
            }
        }
        
        /// <summary>
        /// Add contacts to activities.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Add contacts to activities.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activities/addcontacts")]
        public string AddContactsActivity {
            get {
                return ((string)(this["AddContactsActivity"]));
            }
        }
        
        /// <summary>
        /// Access a contact.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access a contact.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}")]
        public string Contact {
            get {
                return ((string)(this["Contact"]));
            }
        }
        
        /// <summary>
        /// Get all contacts.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get all contacts.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts")]
        public string Contacts {
            get {
                return ((string)(this["Contacts"]));
            }
        }
        
        /// <summary>
        /// Get all lists.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get all lists.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lists")]
        public string Lists {
            get {
                return ((string)(this["Lists"]));
            }
        }
        
        /// <summary>
        /// Access a specified list.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access a specified list.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lists/{0}")]
        public string List {
            get {
                return ((string)(this["List"]));
            }
        }
        
        /// <summary>
        /// Get the list of contacts from a list.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get the list of contacts from a list.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lists/{0}/contacts")]
        public string ListContacts {
            get {
                return ((string)(this["ListContacts"]));
            }
        }
        
        /// <summary>
        /// Get contact lists.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get contact lists.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/lists")]
        public string ContactLists {
            get {
                return ((string)(this["ContactLists"]));
            }
        }
        
        /// <summary>
        /// Get a list from contact lists.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get a list from contact lists.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/lists/{1}")]
        public string ContactList {
            get {
                return ((string)(this["ContactList"]));
            }
        }
        
        /// <summary>
        /// Get campaigns.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get campaigns.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns")]
        public string Campaigns {
            get {
                return ((string)(this["Campaigns"]));
            }
        }
        
        /// <summary>
        /// Access a campaign
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access a campaign")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}")]
        public string Campaign {
            get {
                return ((string)(this["Campaign"]));
            }
        }
        
        /// <summary>
        /// Campaign schedules.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign schedules.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/schedules")]
        public string CampaignSchedules {
            get {
                return ((string)(this["CampaignSchedules"]));
            }
        }
        
        /// <summary>
        /// Campaign schedule.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign schedule.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/schedules/{1}")]
        public string CampaignSchedule {
            get {
                return ((string)(this["CampaignSchedule"]));
            }
        }
        
        /// <summary>
        /// Campaign test sends.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign test sends.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tests")]
        public string CampaignTestSends {
            get {
                return ((string)(this["CampaignTestSends"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking summary.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking summary.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/reports/summary")]
        public string CampaignTrackingSummary {
            get {
                return ((string)(this["CampaignTrackingSummary"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking bounces.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking bounces.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/bounces")]
        public string CampaignTrackingBounces {
            get {
                return ((string)(this["CampaignTrackingBounces"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking clicks.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking clicks.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/clicks")]
        public string CampaignTrackingClicks {
            get {
                return ((string)(this["CampaignTrackingClicks"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking clicks for a specific link.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking clicks for a specific link.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/clicks/{1}")]
        public string CampaignTrackingClicksForLink {
            get {
                return ((string)(this["CampaignTrackingClicksForLink"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking forwards.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking forwards.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/forwards")]
        public string CampaignTrackingForwards {
            get {
                return ((string)(this["CampaignTrackingForwards"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking opens.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking opens.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/opens")]
        public string CampaignTrackingOpens {
            get {
                return ((string)(this["CampaignTrackingOpens"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking sends.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking sends.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/sends")]
        public string CampaignTrackingSends {
            get {
                return ((string)(this["CampaignTrackingSends"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking unsubscribes.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking unsubscribes.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/unsubscribes")]
        public string CampaignTrackingUnsubscribes {
            get {
                return ((string)(this["CampaignTrackingUnsubscribes"]));
            }
        }
        
        /// <summary>
        /// Campaign tracking link.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Campaign tracking link.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/tracking/clicks/{1}")]
        public string CampaignTrackingLink {
            get {
                return ((string)(this["CampaignTrackingLink"]));
            }
        }
        
        /// <summary>
        /// Contact tracking activities.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking activities.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking")]
        public string ContactTrackingActivities {
            get {
                return ((string)(this["ContactTrackingActivities"]));
            }
        }
        
        /// <summary>
        /// Contact tracking activities by email campaign.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking activities by email campaign.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/reports/summaryByCampaign")]
        public string ContactTrackingEmailCampaignActivities {
            get {
                return ((string)(this["ContactTrackingEmailCampaignActivities"]));
            }
        }
        
        /// <summary>
        /// Contact tracking summary.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking summary.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/reports/summary")]
        public string ContactTrackingSummary {
            get {
                return ((string)(this["ContactTrackingSummary"]));
            }
        }
        
        /// <summary>
        /// Contact tracking bounces.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking bounces.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/bounces")]
        public string ContactTrackingBounces {
            get {
                return ((string)(this["ContactTrackingBounces"]));
            }
        }
        
        /// <summary>
        /// Contact tracking clicks.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking clicks.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/clicks")]
        public string ContactTrackingClicks {
            get {
                return ((string)(this["ContactTrackingClicks"]));
            }
        }
        
        /// <summary>
        /// Contact tracking forwards.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking forwards.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/forwards")]
        public string ContactTrackingForwards {
            get {
                return ((string)(this["ContactTrackingForwards"]));
            }
        }
        
        /// <summary>
        /// Contact tracking opens.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking opens.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/opens")]
        public string ContactTrackingOpens {
            get {
                return ((string)(this["ContactTrackingOpens"]));
            }
        }
        
        /// <summary>
        /// Contact tracking sends.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking sends.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/sends")]
        public string ContactTrackingSends {
            get {
                return ((string)(this["ContactTrackingSends"]));
            }
        }
        
        /// <summary>
        /// Contact tracking unsubscribes.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking unsubscribes.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/unsubscribes")]
        public string ContactTrackingUnsubscribes {
            get {
                return ((string)(this["ContactTrackingUnsubscribes"]));
            }
        }
        
        /// <summary>
        /// Contact tracking link.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Contact tracking link.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/{0}/tracking/clicks/{1}")]
        public string ContactTrackingLink {
            get {
                return ((string)(this["ContactTrackingLink"]));
            }
        }
        
        /// <summary>
        /// Account verified email addresses link
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Account verified email addresses link")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("account/verifiedemailaddresses")]
        public string AccountVerifiedEmailAddressess {
            get {
                return ((string)(this["AccountVerifiedEmailAddressess"]));
            }
        }
        
        /// <summary>
        /// Account Summary Information
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Account Summary Information")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("account/info")]
        public string AccountSummaryInformation {
            get {
                return ((string)(this["AccountSummaryInformation"]));
            }
        }
        
        /// <summary>
        /// MyLibrary information
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrary information")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/info")]
        public string MyLibraryInfo {
            get {
                return ((string)(this["MyLibraryInfo"]));
            }
        }
        
        /// <summary>
        /// MyLibrary folders
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrary folders")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/folders")]
        public string MyLibraryFolders {
            get {
                return ((string)(this["MyLibraryFolders"]));
            }
        }
        
        /// <summary>
        /// Access a specified folder
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Access a specified folder")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/folders/{0}")]
        public string MyLibraryFolder {
            get {
                return ((string)(this["MyLibraryFolder"]));
            }
        }
        
        /// <summary>
        /// Files in Trash folder
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Files in Trash folder")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/folders/trash/files")]
        public string MyLibraryTrash {
            get {
                return ((string)(this["MyLibraryTrash"]));
            }
        }
        
        /// <summary>
        /// MyLibrray files
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrray files")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/files")]
        public string MyLibraryFiles {
            get {
                return ((string)(this["MyLibraryFiles"]));
            }
        }
        
        /// <summary>
        /// MyLibrary file
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrary file")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/files/{0}")]
        public string MyLibraryFile {
            get {
                return ((string)(this["MyLibraryFile"]));
            }
        }
        
        /// <summary>
        /// MyLibrary files for a specific folder
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrary files for a specific folder")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/folders/{0}/files")]
        public string MyLibraryFolderFiles {
            get {
                return ((string)(this["MyLibraryFolderFiles"]));
            }
        }
        
        /// <summary>
        /// MyLibrary file upload status
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("MyLibrary file upload status")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("library/files/uploadstatus/{0}")]
        public string MyLibraryFileUploadStatus {
            get {
                return ((string)(this["MyLibraryFileUploadStatus"]));
            }
        }
        
        /// <summary>
        /// EventSpot Events Collection Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("EventSpot Events Collection Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events")]
        public string EventSpots {
            get {
                return ((string)(this["EventSpots"]));
            }
        }
        
        /// <summary>
        /// Individual Event Fees Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Individual Event Fees Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events/{0}/fees/{1}")]
        public string EventFees {
            get {
                return ((string)(this["EventFees"]));
            }
        }
        
        /// <summary>
        /// Individual Promocode Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Individual Promocode Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events/{0}/promocodes/{1}")]
        public string EventPromocode {
            get {
                return ((string)(this["EventPromocode"]));
            }
        }
        
        /// <summary>
        /// Individual Event Registrant Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Individual Event Registrant Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events/{0}/registrants/{1}")]
        public string EventRegistrant {
            get {
                return ((string)(this["EventRegistrant"]));
            }
        }
        
        /// <summary>
        /// Event Item Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Event Item Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events/{0}/items/{1}")]
        public string EventItem {
            get {
                return ((string)(this["EventItem"]));
            }
        }
        
        /// <summary>
        /// Item Attribute Endpoint
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Item Attribute Endpoint")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eventspot/events/{0}/items/{1}/attributes/{2}")]
        public string ItemAttribute {
            get {
                return ((string)(this["ItemAttribute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailmarketing/campaigns/{0}/preview")]
        public string EmailCampaignPreview {
            get {
                return ((string)(this["EmailCampaignPreview"]));
            }
        }
    }
}
