//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTCT.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or Activity are allowed for this method..
        /// </summary>
        internal static string ActivityOrId {
            get {
                return ResourceManager.GetString("ActivityOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or CampaignTracking are allowed for this method..
        /// </summary>
        internal static string CampaignTrackingOrId {
            get {
                return ResourceManager.GetString("CampaignTrackingOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or Contact are allowed for this method..
        /// </summary>
        internal static string ContactOrId {
            get {
                return ResourceManager.GetString("ContactOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or ContactTracking are allowed for this method..
        /// </summary>
        internal static string ContactTrackingOrId {
            get {
                return ResourceManager.GetString("ContactTrackingOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or EmailCampaign are allowed for this method..
        /// </summary>
        internal static string EmailCampaignOrId {
            get {
                return ResourceManager.GetString("EmailCampaignOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must not be null.
        /// </summary>
        internal static string FieldNull {
            get {
                return ResourceManager.GetString("FieldNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Id parameter must not be null.
        /// </summary>
        internal static string FileIdNull {
            get {
                return ResourceManager.GetString("FileIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a FileName parameter for this method..
        /// </summary>
        internal static string FileNameNull {
            get {
                return ResourceManager.GetString("FileNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a File parameter for this method..
        /// </summary>
        internal static string FileNull {
            get {
                return ResourceManager.GetString("FileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is invalid..
        /// </summary>
        internal static string FileTypeInvalid {
            get {
                return ResourceManager.GetString("FileTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an valid id is allowed for this method..
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Webhook. The x-ctct-hmac-sha256 does not correspond to message encryption..
        /// </summary>
        internal static string InvalidWebhook {
            get {
                return ResourceManager.GetString("InvalidWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or ContactList are allowed for this method..
        /// </summary>
        internal static string ListOrId {
            get {
                return ResourceManager.GetString("ListOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or a MyLibrary item is allowed for this method..
        /// </summary>
        internal static string MyLibraryOrId {
            get {
                return ResourceManager.GetString("MyLibraryOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the client secret (via constructor or setClientSecret() ) corresponding to your API   from Constant Contact.
        /// </summary>
        internal static string NoClientSecret {
            get {
                return ResourceManager.GetString("NoClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object provided is not valid..
        /// </summary>
        internal static string ObjectNull {
            get {
                return ResourceManager.GetString("ObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an interger or Schedule are allowed for this method..
        /// </summary>
        internal static string ScheduleOrId {
            get {
                return ResourceManager.GetString("ScheduleOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a contact ID in order to update a contact..
        /// </summary>
        internal static string UpdateId {
            get {
                return ResourceManager.GetString("UpdateId", resourceCulture);
            }
        }
    }
}
